apiVersion:  argoproj.io/v1alpha1
kind:  Application
metadata:  
  name:  testapp 
  namespace:  argocd
spec:  
  project:  default
  source:  
    repoURL: git@github.com:icdckl2020/helmSecretTest.git   
    targetRevision:  master
    path:  helmsecret
    helm:
      releaseName: testapp
      valueFiles:
        - "secrets.yaml"
  destination:  
    server:  https://kubernetes.default.svc
    namespace:  default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true