apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmsecret
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helmsecret
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
        releaseName: helmsecret
        valueFiles:
          - "secrets.yaml"